refactor: update create rating
meta-build/Projeto-IONIC-Health pull request #13
Opened 2023-05-08 11:37 UTC by Rafael-Caje

2023-05-08 19:47 UTC, gabriel-fabian requested changes
Top man, só uns detalhes como mencionei

2023-05-08 19:47 UTC, gabriel-fabian commented on backend/src/application/controllers/rating/create-rating-controller.ts
>  import { Rating, Ticket, User } from '@/infra/repositories/mysql/entities'
Esses imports deixaram de ser utilizados.

```suggestion
import { Rating } from '@/infra/repositories/mysql/entities'
```

2023-05-08 19:47 UTC, gabriel-fabian commented on backend/src/application/controllers/rating/create-rating-controller.ts
> +    }
Isso é firula mas tem uns espaços em branco aqui.

```suggestion
    if (!reviewer) {
      return badRequest(new UnauthorizedError)
    }

    const ticket = await this.ticketRepository.loadTicketById({ id: ticketId })

    if (!ticket) {
      return badRequest(new UnauthorizedError)
    }
```

2023-05-08 19:47 UTC, gabriel-fabian commented on backend/src/application/controllers/rating/create-rating-controller.ts
>      await AppDataSource.manager.save(Rating, rating)
Essa lógica de salvar foi pra dentro do RatingRepository, no caso deixar isso aqui duplica o Rating.

```suggestion
```

2023-05-08 19:47 UTC, gabriel-fabian commented on backend/src/domain/contracts/repos/rating.ts
> +}
Aqui foi uma questão de lint, todo arquivo tem que ter uma linha em branco no fim se não o Git reclama. E utilizei identação com tabs e 2 espaços

```suggestion
export interface CreateRating {
  create: (input: CreateRating.Input) => Promise<CreateRating.Output>
}

export namespace CreateRating {
  export type Input = {
    requesterId: number
    value: number
    committee: string
    comment: string
    ticketId: number
  }
  export type Output = {
    id: number
    userId: number
    value: number
    committee: string
    comment: string
    ticketId: number
  }
}
export interface LoadRatingByReqId {
  loadByReqId: (
    input: LoadRatingByReqId.Input
  ) => Promise<LoadRatingByReqId.Output>
}

export namespace LoadRatingByReqId {
  export type Input = {
    requesterId: number
  }
  export type Output = {
    id: number
    userId: number
    value: number
    committee: string
    comment: string
    ticketId: number
  }
}

```

2023-05-08 19:47 UTC, gabriel-fabian commented on backend/src/domain/contracts/repos/ticket.ts
> +}
Mesma coisa que o rating.ts

```suggestion
export interface CreateTicket {
  create: (input: CreateTicket.Input) => Promise<CreateTicket.Output>
}

export namespace CreateTicket {
  export type Input = {
    title: string
    type: string
    description: string
  }
  export type Output = {
    id: number
    title: string
    type: string
    description: string
  }
}

export interface LoadTicketByReqId {
  loadTicketById: (
    input: LoadTicketByReqId.Input
  ) => Promise<LoadTicketByReqId.Output>
}

export namespace LoadTicketByReqId {
  export type Input = {
    id: number
  }
  export type Output = {
    id: number
    title: string
    type: string
    description: string
  }
}

```

2023-05-08 19:47 UTC, gabriel-fabian commented on backend/src/infra/repositories/mysql/rating-repository.ts
> +}
Além do Lint o loadByReqId não está sendo usado em lugar algum.

```suggestion
import { Rating } from './entities'
import DataSource from './data-source'
import {
  CreateRating,
  LoadRatingByReqId
} from '@/domain/contracts/repos/rating'

import { ObjectType, Repository } from 'typeorm'

export class RatingRepository implements CreateRating, LoadRatingByReqId {
  getRepository(entity: ObjectType<Rating>): Repository<Rating> {
    return DataSource.getRepository(entity)
  }

  async create({
    requesterId,
    value,
    committee,
    comment,
    ticketId
  }: CreateRating.Input): Promise<CreateRating.Output> {
    const ratingRepo = this.getRepository(Rating)
    const rating = ratingRepo.create({
      userId: requesterId,
      value,
      committee,
      comment,
      ticketId
    })

    await ratingRepo.save(rating)

    return {
      id: rating.id,
      userId: rating.userId,
      value: rating.value,
      committee: rating.committee,
      comment: rating.comment,
      ticketId: rating.ticketId
    }
  }

  async loadByReqId({
    requesterId
  }: LoadRatingByReqId.Input): Promise<LoadRatingByReqId.Output> {
    const ratingRepo = this.getRepository(Rating)

    const rating = await ratingRepo.findOneBy({ id: requesterId })

    if (rating) {
      return rating
    }

    return null
  }
}

```

2023-05-08 19:47 UTC, gabriel-fabian commented on backend/src/infra/repositories/mysql/ticket-repository.ts
> +}
Além do Lint o create não está sendo usado em lugar algum.

```suggestion
import { Ticket } from './entities'
import DataSource from './data-source'
import {
  CreateTicket,
  LoadTicketByReqId
} from '@/domain/contracts/repos/ticket'

import { ObjectType, Repository } from 'typeorm'

export class TicketRepository implements CreateTicket, LoadTicketByReqId {
  getRepository(entity: ObjectType<Ticket>): Repository<Ticket> {
    return DataSource.getRepository(entity)
  }

  async create({
    title,
    type,
    description
  }: CreateTicket.Input): Promise<CreateTicket.Output> {
    const ticketRepo = this.getRepository(Ticket)
    const ticket = ticketRepo.create({
      title,
      type,
      description
    })

    await ticketRepo.save(ticket)

    return {
      id: ticket.id,
      title: ticket.title,
      type: ticket.type,
      description: ticket.description
    }
  }

  async loadTicketById({
    id
  }: LoadTicketByReqId.Input): Promise<LoadTicketByReqId.Output> {
    const ticketRepo = this.getRepository(Ticket)

    const ticket = await ticketRepo.findOneBy({ id })

    if (ticket) {
      return ticket
    }

    return null
  }
}

```

2023-05-08 19:47 UTC, gabriel-fabian commented on backend/src/main/factories/application/controllers/rating/create-rating-controller-factory.ts
> +import { TicketRepository } from '@/infra/repositories/mysql/ticket-repository'
Aqui dá pra fazer um refactor da seguinte forma:

Cria uma pasta repositories em `infra/repositories/mysql/` e move todos os `repository` para dentro dela.

Cria um `index.ts` na pasta mysql com o seguinte:

```typescript
export * from './repositores/rating-repository'
export * from './repositories/ticket-repository'
export * from './repositories/user-repository'

```

Com isso é possível alterar esses imports para:

```suggestion
import { UserRepository, RatingRepository, TicketRepository } from '@/infra/repositories/mysql'
```

2023-05-08 19:56 UTC, gabriel-fabian commented on backend/src/application/controllers/rating/create-rating-controller.ts
> +      return badRequest(new UnauthorizedError)
Aqui eu havia dado um exemplo de retornar badRequest, mas nesse caso seria outro. O que faz sentido aqui é o UnprocessableEntity - 422.

Você vai ter que criar ele em `application/helpers/http.ts`

```typescript
export const unprocessableEntity = (): HttpResponse<Error> => ({
  statusCode: 422,
  data: new UnprocessableEntity
})
```

A Classe `UnprocessableEntity` você define em `application/errors/http.ts`

```typescript
export class UnprocessableEntity extends Error {
  constructor () {
    super('Unprocessable Entity')
    this.name = 'UnprocessableEntity'
  }
}
```

2023-05-12 05:23 UTC, Rafael-Caje commented on backend/src/application/controllers/rating/create-rating-controller.ts
> +      return badRequest(new UnauthorizedError)
Novo erro criado e substituído conforme sugestão.

2023-05-12 21:43 UTC, gabriel-fabian approved these changes

2023-05-12 21:47 UTC, merged