refactor: update GetTicketByIdController
meta-build/Projeto-IONIC-Health pull request #14
Opened 2023-05-09 01:46 UTC by William2819

2023-05-09 13:34 UTC, gabriel-fabian requested changes
Top man, deixei alguns pontos aí pra alterar.

2023-05-11 01:58 UTC, William2819 commented on backend/src/application/controllers/ticket/get-ticket-by-id-controller.ts
>    public async getTicketById(req: Request, res: Response) {
acho que esse método é do antigo, não está no meu repositório

2023-05-11 02:06 UTC, William2819 commented on backend/src/infra/repositories/mysql/ticket-repository.ts
> +    async create({
da erro ao remover

2023-05-12 20:32 UTC, gabriel-fabian approved these changes

2023-05-12 20:41 UTC, merged